### ISSUE TITLE
files hosted on `cdnjs`

### ISSUE THREAD

**Issue by maruilian11** [crossfilter/reductio#39]
hi, recently we want to host you lib on https://cdnjs.com, i want to confirm if these files 
`./build.js`
`./accessors.js`
`./parameters.js`
`./postprocess`
are also need to be hosted on cdnjs.
https://github.com/crossfilter/reductio/blob/master/reductio.js#L6
thank you very much!

https://github.com/cdnjs/cdnjs/pull/7555#discussion_r64998873
https://github.com/cdnjs/cdnjs/issues/7434

**Comment by esjewett** [comment]
I think only the reductio.js and reductio.min.js files in the root directory are needed. I see the comment about reductio.js not working in the browser and I'm not sure if this is the case and there is a build problem in the project or if it will actually work. I probably won't have time to check this week, but I'll try.

**Comment by maruilian11** [comment]
thank you and take your time.

**Comment by esjewett** [comment]
It seems to me that reductio.js works fine. Example here (see the console): https://jsfiddle.net/esjewett/aohqjhy6/

I believe the confusion may be because I use Browserify in the build process, which provides an implementation of `require` in the browser (though it works quite differently from the native `require` in CommonJS).
